config/routes.rb
Orc::Application.routes.draw do

  match "search/visitors" => 'visitors#index'
  get 'visitors/autocomplete_visitor_name'
  get 'visitors/autocomplete_visitor_mobile_no'

  resources :users
  resources :user_sessions
  match 'users/new' => 'users#new', :as => :signup
  match 'user_sessions/logout/:id' => 'user_sessions#logout', :as => :logout
  match 'user_sessions/new' => 'user_sessions#new', :as => :login
  
  get "user_sessions/new"
  get "users/new"
  get "users/edit"
  get "events/create"
  match 'visitors/checkinfacebox/:registration_id' => 'visitors#checkinfacebox', :as => :checkinfacebox_visitor
  match 'visitors/save_and_continue' => 'visitors#save_and_continue', :as => :save_and_continue
  match 'utilities/uploadexcel' => 'utilities#uploadexcel', :as => :uploadexcel
  match 'utilities/user_list' => 'utilities#user_list', :as => :user_list
  match 'utilities/building_list' => 'utilities#building_list', :as => :building_list
  match 'utilities/event_list' => 'utilities#event_list', :as => :event_list
  match 'utilities/usr_load' => 'utilities#usr_load', :as => :usr_load
  match 'utilities/visitor_load' => 'utilities#visitor_load', :as => :visitor_load
  match 'utilities/cancel_user' => 'utilities#cancel_user', :as => :cancel_user
  match 'utilities/building_load' => 'utilities#building_load', :as => :building_load
  match 'utilities/cancel_building' => 'utilities#cancel_building', :as => :cancel_building
  match 'utilities/event_load' => 'utilities#event_load', :as => :event_load
  match 'utilities/cancel_event' => 'utilities#cancel_event', :as => :cancel_event
  match 'utilities/download_user_list' => 'utilities#download_user_list', :as => :download_user_list
  match 'utilities/download_visitor_list' => 'utilities#download_visitor_list', :as => :download_visitor_list
  match 'utilities/download_building_list' => 'utilities#download_building_list', :as => :download_building_list
  match 'utilities/download_event_list' => 'utilities#download_event_list', :as => :download_event_list
  match 'buildings/add_rooms_to_building/:building_id' => 'buildings#add_rooms_to_building', :as => :add_rooms_to_building
  match 'buildings/add_rooms_to_building_view/:building_id' => 'buildings#add_rooms_to_building_view', :as => :add_rooms_to_building_view
  resources :utilities

  match 'events/:id/participants' => 'events#participants' , :as => :event_participants

     match 'home/index_list' => 'home#index_list', :as => :index_list

  resources :visitors do
    collection do
      post :add_fields_1
      post :add_fields_2
      post :additional_info
      post :add_accompany_info
    end
  end
  
  resources :checkins
  post 'checkins/inactivate/:id' => "checkins#inactivate", :as => :inactivate_checkin
  get 'checkins/print/:id' => "checkins#print", :as => :print_checkin
  
  resources :events 
  post 'events/inactivate/:id' => "events#inactivate", :as => :inactivate_event
  post 'events/activate/:id' => "events#activate", :as => :activate_event

  resources :accompany_visitors
  resources :registrations
  resources :buildings
  resources :rooms
  resources :checkins do
    collection do
      post :roomsearch
    end
  end
 

  get 'javascripts/checkin' => 'javascripts#checkin'
  get 'javascripts/visitor' => 'javascripts#visitor'
  get 'javascripts/event' => 'javascripts#event'
  get 'javascripts/regform' => 'javascripts#regform'

  

  root :to => "user_sessions#new"

end

app/controllers/utilities_controller.rb
class UtilitiesController < ApplicationController
  require 'mime/types'
  require 'spreadsheet'

  def index
  end

  def user_list
  end

  def cancel_building
    flash[:notice] = nil
    render 'index'
  end

  def cancel_user
    flash[:notice] = nil
    render 'index'
  end

  def cancel_event
    flash[:notice] = nil
    render 'index'
  end

  def download_user_list
    handleDownload "UsersList_Template.xls"
    return
  end

  def download_building_list
    handleDownload "BuildingList_Template.xls"
    return
  end

  def download_event_list
    handleDownload "EventList_Template.xls"
    return
  end

  def download_visitor_list
    handleDownload "VisitorList_Template.xls"
    return
  end

  def building_load
    flash[:notice] = nil
    unique_file_name = params[:id]
    ##directory = "#{RAILS_ROOT}/public/uploads/building_list"
    directory = "#{RAILS_ROOT}/tmp"
    full_file_name = File.join(directory,unique_file_name)
    buildings_rooms = extract_buildings_from_excel(full_file_name)
    successful_loaded_rooms = 0
    buildings_rooms.length.times do |br|
      if ! buildings_rooms[br][:isbad]
        #temp_build = Building.find_by_sql("select * from buildings where is_delete = ? and upper(name) = upper('#{buildings_rooms[br][:building_name]}')", false)
        building = Building.find(:first, :conditions => ["upper(name) = upper('#{buildings_rooms[br][:building_name]}')", "is_delete = false"  ] )

        if building.nil?
          new_building = Building.new(:name => buildings_rooms[br][:building_name], :no_of_rooms => 0, :floors => 0, :is_delete => false)
          if new_building.save
            building = new_building
          else
            flash[:notice] = "#ERROR#Fatal Error (#{new_building.errors.full_messages[0]||''}) While Saving Building. Contact Admin !! Reference: #{unique_file_name}"
            next
          end
        end

        room = Room.new()
        room[:floor] = buildings_rooms[br][:floor]
        room[:category] = buildings_rooms[br][:category]
        room.building = building
        room[:room_no] = buildings_rooms[br][:room_name].to_i == 0 ? buildings_rooms[br][:room_name] : buildings_rooms[br][:room_name].to_i
        room[:total_beds] = buildings_rooms[br][:total_beds]
        room[:is_delete] = false 
        if room.save
          room.update_attribute(:is_ac,buildings_rooms[br][:is_ac])
          room.update_attribute(:is_extensible,buildings_rooms[br][:is_extensible])
          room.update_attribute(:beds_extensible,buildings_rooms[br][:beds_extensible]||0)
          room.update_attribute(:occupied_beds,buildings_rooms[br][:occupied_beds]||0)
          room.update_attribute(:empty_beds,"#{buildings_rooms[br][:occupied_beds].nil? ? buildings_rooms[br][:total_beds] : buildings_rooms[br][:total_beds].to_i - buildings_rooms[br][:occupied_beds].to_i}")
          #no_of_rooms_in_building = Room.find_by_sql("select count(room_no) as ct from rooms where is_delete = ? and building_id = #{temp_build_id}", false)
          #no_of_floors_in_building = Room.find_by_sql("select max(floor) as flr from rooms where is_delete = ? and building_id= #{temp_build_id}", false)
          #building.update_attribute(:no_of_rooms,no_of_rooms_in_building[0][:ct])
          #building.update_attribute(:floors,no_of_floors_in_building[0][:flr])
          successful_loaded_rooms += 1
        else
          flash[:notice] = "#ERROR#Fatal Error (#{room.errors.full_messages[0]||''}) While Saving Rooms. Contact Admin !! Reference: #{unique_file_name}"
          next
        end
      end
    end
    flash[:notice] = flash[:notice]||"#{ successful_loaded_rooms==0 ? 'No ' : successful_loaded_rooms} Records Loaded Successfully !!"
    render 'index'
  end

  def visitor_load
    flash[:notice] = nil
    unique_file_name = params[:id]
    ##directory = "#{RAILS_ROOT}/public/uploads/visitor_list"
    directory = "#{RAILS_ROOT}/tmp"
    full_file_name = File.join( directory, unique_file_name)
    visitors = extract_visitors_from_excel(full_file_name)

    @successful_loaded = 0
    visitors.each do |visitor|
      if ! visitor[:isbad]
        event_id = visitor[:event_id]
        event = Event.where(:id => event_id).first
        visitor.delete(:isbad)
        visitor.delete(:comment)
        visitor.delete(:event)
        visitor.delete(:event_id)
    
        if visitor[:existing_visitor_id]
          @visitor_for_reg = Visitor.find visitor[:existing_visitor_id]
        else
          @visitor_for_reg = Visitor.new(visitor)
          @visitor_for_reg.save
        end

#@new_visitor = Visitor.new(visitor)
#if @new_visitor.save
          @registration = Registration.new()
          @registration.visitor = @visitor_for_reg
          @registration.event = event
          @registration.save
          @successful_loaded += 1
#else
#flash[:notice] = "#ERROR#Fatal Error (#{@new_visitor.errors.full_messages[0]||''}) in Visitors. Please Contact Admin. Reference: #{unique_file_name}"
#end
      end
    end  
    flash[:notice] = flash[:notice]||"#{ @successful_loaded ==0 ? 'No ' : @successful_loaded} Records Loaded Successfully !!"
    render 'index'
  end

  def usr_load
    flash[:notice] = nil
    unique_file_name = params[:id]
    ##directory = "#{RAILS_ROOT}/public/uploads/user_list"
    directory = "#{RAILS_ROOT}/tmp"
    full_file_name = File.join(directory,unique_file_name)
    users = extract_users_from_excel(full_file_name)
    @successful_loaded_users = 0
    users.length.times do |us|
      if ! users[us][:isbad]
        @new_user = User.new()
        @new_user.username = users[us][:username]
        @new_user.email = users[us][:email]
        @new_user.role_id = users[us][:role_id]
        @new_user.password = users[us][:password]
        @new_user.password_confirmation = users[us][:password]
        if @new_user.save
          @successful_loaded_users += 1
          user_roles = UsersRoles.new()
          user_roles.user_id = @new_user.id
          user_roles.role_id = @new_user.role_id
          if ! user_roles.save
            flash[:notice] = "#ERROR#Fatal Error (#{user_roles.errors.full_messages[0]||''}) in USERS_ROLES!! Contact Admin !! Reference: #{unique_file_name}"
          end
        else
          flash[:notice] = "#ERROR#Fatal Error (#{@new_user.errors.full_messages[0]||''}) in USERS!! Contact Admin !! Reference: #{unique_file_name}"
        end
      end
    end  
    flash[:notice] = flash[:notice]||"#{ @successful_loaded_users==0 ? 'No ' : @successful_loaded_users} Records Loaded Successfully !!"
    render 'index'
  end

  def event_load
    flash[:notice] = nil
    unique_file_name = params[:id]
    ##directory = "#{RAILS_ROOT}/public/uploads/event_list"
    directory = "#{RAILS_ROOT}/tmp"
    full_file_name = File.join(directory,unique_file_name)
    events = extract_events_from_excel(full_file_name)
    @successful_loaded_events = 0
   events.length.times do |event|
      if ! events[event][:isbad]
        @new_event = Event.new()
        @new_event.name = events[event][:event_name]
        @new_event.start_date_time = events[event][:event_start_date]
        @new_event.end_date_time = events[event][:event_end_date]
        @new_event.location = events[event][:location]
        @new_event.capacity = events[event][:capacity].to_i
        @new_event.is_delete = false
        if @new_event.save
          @successful_loaded_events += 1
        else
          flash[:notice] = "#ERROR#Fatal Error (#{@new_event.errors.full_messages[0]||''}) in Events. Please Contact Admin. Reference: #{unique_file_name}"
        end
      end
    end
    flash[:notice] = flash[:notice]||"#{ @successful_loaded_events ==0 ? 'No ' : @successful_loaded_events} Records Loaded Successfully !!"
    render 'index'
  end

  def uploadexcel
    # file_name_user_list = params[:upload_user_list_file][:user_list_file]||"No File !!"
    # file_name_building_list = params[:upload_building_list_file][:building_list_file]||"No File !!"
    # file_name_event_list = params[:upload_event_list_file][:event_list_file]||"No File !!"
    # params[:id] in {upload_user_list,upload_building_list,upload_event_list,download_user_list,download_building_list,download_event_list}
    flash[:notice] = nil
    if (! params[:upload_user_list_file].nil?) && (! params[:upload_user_list_file][:user_list_file].nil?)
      file = params[:upload_user_list_file][:user_list_file]
      handleUploadUserList(file)
      return
    elsif (! params[:upload_visitor_list_file].nil?) && (! params[:upload_visitor_list_file][:visitor_list_file].nil?)
      file = params[:upload_visitor_list_file][:visitor_list_file]
      handleUploadVisitorList(file)
      return
    elsif (! params[:upload_building_list_file].nil?) && (! params[:upload_building_list_file][:building_list_file].nil?)
      file = params[:upload_building_list_file][:building_list_file]
      handleUploadBuildingList(file)
      return
    elsif (! params[:upload_event_list_file].nil?) && (! params[:upload_event_list_file][:event_list_file].nil?)
      file = params[:upload_event_list_file][:event_list_file]
      handleUploadEventList(file)
      return
    else
      flash[:notice] = "#ERROR# Please choose the file first and then upload !!"
      render 'index'
    end
    return
  end

  private

  def check_users_for_errors(users)
    email_list = User.find_by_sql("select distinct trim(email) as email from users where is_delete = ?", false)
    users.length.times do |us|
      existing_user = User.find(:first,:conditions => ["username = ?", users[us][:username]])
      if users[us][:username].nil? || users[us][:email].nil? || users[us][:role_id].nil? || users[us][:password].nil? || users[us][:role].nil?
        users[us][:isbad] = true
        users[us][:comment] = "No Fields Should Be Blank !!"
      end
      if ! email_list.detect{|em| em.email == users[us][:email]}.nil?
        users[us][:isbad] = true
        users[us][:comment] = "Email already exists !!"
      end

app/helpers/utilities_helper.rb
module UtilitiesHelper
end

app/views/utilities/building_list.html.haml
= render "shared/flash_messages"
%br
%div{:class=>"mid_bg_add_utilities_b padd25bt padd20tp-1", :cellspacing=>"2", :cellpadding=>"2"}
  %table{:class => "table-structure", :cellpadding=>"0", :cellspacing=>"0", :border=>0}
    %tbody
      %tr
        %td{:colspan => "10", :align => "center", :style => "font-size: 13px;background-color:#064B70;color:#FFFFFF"}
          %u
            %b Kindly note down the file name for future reference: 
          &nbsp;&nbsp;&nbsp;
          = @unique_file_name
      %tr 
        %td
          %b &nbsp;&nbsp;&nbsp; 
          = form_tag building_load_path(:id => @unique_file_name), :method => 'post', :multipart => "true" do
            = submit_tag " Continue To Upload.. ", :disable_with => ' Continue To Upload.. '
        %td{:style => "vertical-align:bottom"}
          = button_to " Cancel Upload ", cancel_building_path, :confirm => "Are you sure to abort loading Building data ??"
        %td{:colspan => "8"}
      %tr 
        %td{:colspan => "10"}
          %br
      %tr{:style => "background-color:#3A82F1"} 
        %td
          %b &nbsp;&nbsp;&nbsp; Building Name
        %td
          %b &nbsp;&nbsp;&nbsp; Floor
        %td
          %b &nbsp;&nbsp;&nbsp; Room No
        %td
          %b &nbsp;&nbsp;&nbsp; Is Ac
        %td
          %b &nbsp;&nbsp;&nbsp; Is Ext.
        %td
          %b &nbsp;&nbsp;&nbsp; Beds Ext.
        %td
          %b &nbsp;&nbsp;&nbsp; Total Beds
        %td
          %b &nbsp;&nbsp;&nbsp; Occup. Beds
        %td
          %b &nbsp;&nbsp;&nbsp; Category
        %td
          %b &nbsp;&nbsp;&nbsp; Comment
      %tr 
        - for b_r in @buildings_rooms do
          %tr{:class => cycle('list_line_odd','list_line_even')}
            %td
              &nbsp;&nbsp;&nbsp;
              = b_r[:building_name]
            %td
              &nbsp;&nbsp;&nbsp;
              = "#{if !b_r[:floor].nil? then b_r[:floor].to_i else nil end}"
            %td
              &nbsp;&nbsp;&nbsp;
              = "#{b_r[:room_name].to_i == 0 ? b_r[:room_name] : b_r[:room_name].to_i}"
            %td
              &nbsp;&nbsp;&nbsp;
              = "#{b_r[:is_ac].to_s.capitalize}"
            %td
              &nbsp;&nbsp;&nbsp;
              = "#{b_r[:is_extensible].to_s.capitalize}"
            %td
              &nbsp;&nbsp;&nbsp;
              = "#{if !b_r[:beds_extensible].nil? then b_r[:beds_extensible].to_i else nil end}"
            %td
              &nbsp;&nbsp;&nbsp;
              = "#{if !b_r[:total_beds].nil? then b_r[:total_beds].to_i else nil end}"
            %td
              &nbsp;&nbsp;&nbsp;
              = "#{if !b_r[:occupied_beds].nil? then b_r[:occupied_beds].to_i else nil end}"
            %td
              &nbsp;&nbsp;&nbsp;
              = "#{if !b_r[:category].nil? then b_r[:category].to_i else nil end}"
            - if b_r[:isbad]
              %td{:style=>"color:white;font-weight:bold;background-color:red"}
                &nbsp;&nbsp;&nbsp;
                = b_r[:comment]
            - else
              %td{:style=>"color:white;font-weight:bold;background-color:green"}
                &nbsp;&nbsp;&nbsp;
                = b_r[:comment]

app/views/utilities/event_list.html.haml
= render "shared/flash_messages"
%br
%div{:class=>"mid_bg_add_utilities_b padd25bt padd20tp-1", :cellspacing=>"2", :cellpadding=>"2"}
  %table{:class => "table-structure", :cellpadding=>"0", :cellspacing=>"0", :border=>0}
    %tbody
      %tr
        %td{:colspan => "6", :align => "center", :style => "font-size: 13px;background-color:#064B70;color:#FFFFFF"}
          %u
            %b Kindly note down the file name for future reference: 
          &nbsp;&nbsp;&nbsp;
          = @unique_file_name
      %tr 
        %td
          %b &nbsp;&nbsp;&nbsp; 
          = form_tag event_load_path(:id => @unique_file_name), :method => 'post', :multipart => "true" do
            = submit_tag " Continue To Upload.. ", :disable_with => ' Continue To Upload.. '
        %td{:style => "vertical-align:bottom"}
          = button_to " Cancel Upload ", cancel_event_path, :confirm => "Are you sure to abort loading Event information ??"
        %td{:colspan => "4"}
      %tr 
        %td{:colspan => "6"}
          %br
      %tr{:style => "background-color:#3A82F1"} 
        %td
          %b &nbsp;&nbsp;&nbsp; Event Name
        %td
          %b &nbsp;&nbsp;&nbsp; Start Date
        %td
          %b &nbsp;&nbsp;&nbsp; End Date
        %td
          %b &nbsp;&nbsp;&nbsp; Location
        %td
          %b &nbsp;&nbsp;&nbsp; Capacity
        %td
          %b &nbsp;&nbsp;&nbsp; Comment
      %tr 
        - for e in @events do
          %tr{:class => cycle('list_line_odd','list_line_even')}
            %td
              &nbsp;&nbsp;&nbsp;
              = e[:event_name]
            %td
              &nbsp;&nbsp;&nbsp;
              = e[:event_start_date]
            %td
              &nbsp;&nbsp;&nbsp;
              = e[:event_end_date]
            %td
              &nbsp;&nbsp;&nbsp;
              = e[:location]
            %td
              &nbsp;&nbsp;&nbsp;
              = e[:capacity].to_i
            - if e[:isbad]
              %td{:style=>"color:white;font-weight:bold;background-color:red"}
                &nbsp;&nbsp;&nbsp;
                = e[:comment]
            - else
              %td{:style=>"color:white;font-weight:bold;background-color:green"}
                &nbsp;&nbsp;&nbsp;
                = e[:comment]

app/views/utilities/index.html.haml
%div{:class=>"mid_bg_add text_add_6 padd25bt padd20tp-1", :cellspacing=>"2", :cellpadding=>"2", :border=>"0"}
  %table{:class => "table-structure", :cellpadding=>"0", :cellspacing=>"0"}
    %tbody
      %tr 
        %td{:colspan => "4", :align=>"center", :style => "font_weight:bold; color:red"}
          = render "shared/flash_messages"
          %br
      %tr{:bgcolor => "#D6D9BA"}
        %td
          %b &nbsp; &nbsp; &nbsp; 1) Upload Users List:
        %td
          = form_tag uploadexcel_path, :id=> "upload_user_list",:method => 'post', :multipart => "true" do
            %table
              %tbody
                %tr
                  %td
                    = file_field 'upload_user_list_file',:user_list_file, :style=>"color:#FF0055;font_weight:bold"
                  %td
                  %td
                    = submit_tag " View & Upload "
        %td{:align=>"center"}
          = button_to " Download Template ", download_user_list_path
      %tr{:bgcolor => "#808963"}
        %td
          %b &nbsp; &nbsp; &nbsp; 2) Upload Buildings Information:
        %td
          = form_tag uploadexcel_path, :id => "upload_building_list",:method => 'post', :multipart=>true do
            %table
              %tbody
                %tr
                  %td
                    = file_field 'upload_building_list_file',:building_list_file, :style=>"color:#FF0055;font_weight:bold"
                  %td
                  %td
                    = submit_tag " View & Upload ", :disable_with => ' View & Upload '
        %td{:align=>"center"}
          = button_to " Download Template ", download_building_list_path
      %tr{:bgcolor => "#D6D9BA"}
        %td
          %b &nbsp; &nbsp; &nbsp; 3) Upload Events List:
        %td
          = form_tag uploadexcel_path, :id=> "upload_event_list",:method => 'post', :multipart=>true do
            %table
              %tbody
                %tr
                  %td
                    = file_field 'upload_event_list_file',:event_list_file, :style=>"color:#FF0055;font_weight:bold"
                  %td
                  %td
                    = submit_tag " View & Upload ", :disable_with => ' View & Upload '
        %td{:align=>"center"}
          = button_to " Download Template " ,download_event_list_path
      %tr{:bgcolor => "#808963"}
        %td
          %b &nbsp; &nbsp; &nbsp; 4) Upload Visitors List:
        %td
          = form_tag uploadexcel_path, :id=> "upload_visitor_list",:method => 'post', :multipart=>true do
            %table
              %tbody
                %tr
                  %td
                    = file_field 'upload_visitor_list_file',:visitor_list_file, :style=>"color:#FF0055;font_weight:bold"
                  %td
                  %td
                    = submit_tag " View & Upload ", :disable_with => ' View & Upload '
        %td{:align=>"center"}
          = button_to " Download Template " ,download_visitor_list_path

app/views/utilities/user_list.html.haml
= render "shared/flash_messages"
%br
%div{:class=>"mid_bg_add text_add_6 padd25bt padd20tp-1", :cellspacing=>"2", :cellpadding=>"2", :border=>"0"}
  %table{:class => "table-structure", :cellpadding=>"0", :cellspacing=>"0", :border=>0}
    %tbody
      %tr
        %td{:colspan => "5", :align => "center", :style => "font-size: 13px;background-color:#064B70;color:#FFFFFF"}
          %u
            %b Kindly note down the file name for future reference: 
          &nbsp;&nbsp;&nbsp;
          = @unique_file_name
      %tr 
        %td
          %b &nbsp;&nbsp;&nbsp; 
          = form_tag usr_load_path(:id => @unique_file_name), :method => 'post', :multipart => "true" do
            = submit_tag " Continue To Upload.. ", :disable_with => ' Continue To Upload.. '
        %td{:style => "vertical-align:bottom"}
          = button_to " Cancel Upload ", cancel_user_path, :confirm => "Are you sure to abort loading Users data ??"
        %td{:colspan => "3"}
      %tr 
        %td{:colspan => "5"}
          %br
      %tr{:style => "background-color:#3A82F1"} 
        %td
          %b &nbsp;&nbsp;&nbsp; Username
        %td
          %b &nbsp;&nbsp;&nbsp; Email
        %td
          %b &nbsp;&nbsp;&nbsp; Password
        %td
          %b &nbsp;&nbsp;&nbsp; Role
        %td
          %b &nbsp;&nbsp;&nbsp; Comments
      %tr 
        - for user in @users do
          %tr{:class => cycle('list_line_odd','list_line_even')}
            %td
              &nbsp;&nbsp;&nbsp;
              = user[:username]
            %td
              &nbsp;&nbsp;&nbsp;
              = user[:email]
            %td
              &nbsp;&nbsp;&nbsp;
              = user[:password]
            %td
              &nbsp;&nbsp;&nbsp;
              = user[:role]
            - if user[:isbad]
              %td{:style=>"color:white;font-weight:bold;background-color:red"}
                &nbsp;&nbsp;&nbsp;
                = user[:comment]
            - else
              %td{:style=>"color:white;font-weight:bold;background-color:green"}
                &nbsp;&nbsp;&nbsp;
                = user[:comment]

app/views/utilities/visitor_list.html.haml
= render "shared/flash_messages"
%br
%div{:class=>"mid_bg_add text_add_6 padd25bt padd20tp-1", :cellspacing=>"2", :cellpadding=>"2", :border=>"0"}
  %table{:class => "table-structure", :cellpadding=>"0", :cellspacing=>"0", :border=>0}
    %tbody
      %tr
        %td{:colspan => "5", :align => "center", :style => "font-size: 13px;background-color:#064B70;color:#FFFFFF"}
          %u
            %b Kindly note down the file name for future reference: 
          &nbsp;&nbsp;&nbsp;
          = @unique_file_name
      %tr 
        %td
          %b &nbsp;&nbsp;&nbsp; 
          = form_tag visitor_load_path(:id => @unique_file_name), :method => 'post', :multipart => "true" do
            = submit_tag " Continue To Upload.. ", :disable_with => ' Continue To Upload.. '
        %td{:style => "vertical-align:bottom"}
          = button_to " Cancel Upload ", cancel_user_path, :confirm => "Are you sure to abort loading Visitors data ??"
        %td{:colspan => "3"}
      %tr 
        %td{:colspan => "5"}
          %br
      %tr{:style => "background-color:#3A82F1"} 
        %td
          %b &nbsp;&nbsp;&nbsp; Name
        %td
          %b &nbsp;&nbsp;&nbsp; Age
        %td
          %b &nbsp;&nbsp;&nbsp; Gender
        %td
          %b &nbsp;&nbsp;&nbsp; Address
        %td
          %b &nbsp;&nbsp;&nbsp; Mobile
        %td
          %b &nbsp;&nbsp;&nbsp; Event
        %td
          %b &nbsp;&nbsp;&nbsp; Visitor_type
        %td
          %b &nbsp;&nbsp;&nbsp; In Gyan (Years)
        %td
          %b &nbsp;&nbsp;&nbsp; Centre Address
      %tr 
        - for user in @visitors do
          %tr{:class => cycle('list_line_odd','list_line_even')}
            %td
              &nbsp;&nbsp;&nbsp;
              = user[:name]
            %td
              &nbsp;&nbsp;&nbsp;
              = user[:age]
            %td
              &nbsp;&nbsp;&nbsp;
              = user[:gender]
            %td
              &nbsp;&nbsp;&nbsp;
              = user[:address]
            %td
              &nbsp;&nbsp;&nbsp;
              = user[:mobile_no]
            %td
              &nbsp;&nbsp;&nbsp;
              = user[:event]
            %td
              &nbsp;&nbsp;&nbsp;
              = user[:visitor_type]
            %td
              &nbsp;&nbsp;&nbsp;
              = user[:in_gyan_years]
            %td
              &nbsp;&nbsp;&nbsp;
              = user[:centre_addr]
            - if user[:isbad]
              %td{:style=>"color:white;font-weight:bold;background-color:red"}
                &nbsp;&nbsp;&nbsp;
                = user[:comment]
            - else
              %td{:style=>"color:white;font-weight:bold;background-color:green"}
                &nbsp;&nbsp;&nbsp;
                = user[:comment]