config/routes.rb
Orc::Application.routes.draw do

  match "search/visitors" => 'visitors#index'
  get 'visitors/autocomplete_visitor_name'
  get 'visitors/autocomplete_visitor_mobile_no'

  resources :users
  resources :user_sessions
  match 'users/new' => 'users#new', :as => :signup
  match 'user_sessions/logout/:id' => 'user_sessions#logout', :as => :logout
  match 'user_sessions/new' => 'user_sessions#new', :as => :login
  
  get "user_sessions/new"
  get "users/new"
  get "users/edit"
  get "events/create"
  match 'visitors/checkinfacebox/:registration_id' => 'visitors#checkinfacebox', :as => :checkinfacebox_visitor
  match 'visitors/save_and_continue' => 'visitors#save_and_continue', :as => :save_and_continue
  match 'utilities/uploadexcel' => 'utilities#uploadexcel', :as => :uploadexcel
  match 'utilities/user_list' => 'utilities#user_list', :as => :user_list
  match 'utilities/building_list' => 'utilities#building_list', :as => :building_list
  match 'utilities/event_list' => 'utilities#event_list', :as => :event_list
  match 'utilities/usr_load' => 'utilities#usr_load', :as => :usr_load
  match 'utilities/visitor_load' => 'utilities#visitor_load', :as => :visitor_load
  match 'utilities/cancel_user' => 'utilities#cancel_user', :as => :cancel_user
  match 'utilities/building_load' => 'utilities#building_load', :as => :building_load
  match 'utilities/cancel_building' => 'utilities#cancel_building', :as => :cancel_building
  match 'utilities/event_load' => 'utilities#event_load', :as => :event_load
  match 'utilities/cancel_event' => 'utilities#cancel_event', :as => :cancel_event
  match 'utilities/download_user_list' => 'utilities#download_user_list', :as => :download_user_list
  match 'utilities/download_visitor_list' => 'utilities#download_visitor_list', :as => :download_visitor_list
  match 'utilities/download_building_list' => 'utilities#download_building_list', :as => :download_building_list
  match 'utilities/download_event_list' => 'utilities#download_event_list', :as => :download_event_list
  match 'buildings/add_rooms_to_building/:building_id' => 'buildings#add_rooms_to_building', :as => :add_rooms_to_building
  match 'buildings/add_rooms_to_building_view/:building_id' => 'buildings#add_rooms_to_building_view', :as => :add_rooms_to_building_view
  resources :utilities

  match 'events/:id/participants' => 'events#participants' , :as => :event_participants

     match 'home/index_list' => 'home#index_list', :as => :index_list

  resources :visitors do
    collection do
      post :add_fields_1
      post :add_fields_2
      post :additional_info
      post :add_accompany_info
    end
  end
  
  resources :checkins
  post 'checkins/inactivate/:id' => "checkins#inactivate", :as => :inactivate_checkin
  get 'checkins/print/:id' => "checkins#print", :as => :print_checkin
  
  resources :events 
  post 'events/inactivate/:id' => "events#inactivate", :as => :inactivate_event
  post 'events/activate/:id' => "events#activate", :as => :activate_event

  resources :accompany_visitors
  resources :registrations
  resources :buildings
  resources :rooms
  resources :checkins do
    collection do
      post :roomsearch
    end
  end
 

  get 'javascripts/checkin' => 'javascripts#checkin'
  get 'javascripts/visitor' => 'javascripts#visitor'
  get 'javascripts/event' => 'javascripts#event'
  get 'javascripts/regform' => 'javascripts#regform'

  

  root :to => "user_sessions#new"

end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
#  has_many :checkins
  has_many :registrations
  has_many :events, :through => :registrations
#  has_many :accompany_visitors
#  before_create :set_default_values
  
#  def set_default_values
#    self.is_delete = 0
#    self.is_guide = 0
#    self.is_driver_along = 0
#    self.is_driver_accom_req = 0
#    self.is_driver_in_gyan = 0
#    self.is_special_care_req = 0
#    self.is_physically_challenged = 0
#  end

#  attr_accessible :name, :age

  validates :name, :presence => true
  #validates :dob, :presence => true
  validates :age, :presence => true, :numericality => true, :inclusion => (0..100)
  validates :address, :presence => true
  validates :gender, :presence => true
  validates :mobile_no, :presence => true, :length => 6..15, :numericality => true
  #validates :mobile_no, :length => 10..10, :numericality => true, :if => Proc.new { |visitor| visitor.mobile_no != ''}
  validates :visitor_type, :presence => true
  validates :in_gyan_years, :presence => true, :if => Proc.new { |visitor| visitor.visitor_type == 'bk'}, :inclusion => (0..90), :numericality => true
  validates :centre_addr, :presence => true, :if => Proc.new { |visitor| visitor.visitor_type == 'bk'}
#  validates_presence_of :is_physically_challenged
#  validates :is_physically_challenged, :presence => true

# The following code (define_index) is needed by thinking-sphinx gem to index this class
  define_index do 
    indexes :name
    indexes :address
    indexes :centre_addr
    set_property :enable_star => 1
    set_property :min_prefix_len => 2
  end
end

app/controllers/visitor_controller.rb
class VisitorController < ApplicationController
  def new
    @visitor = Visitor.new
    @coll = ["BK" , "Non BK"] #_visitor_types
  end

  def create
    @visitor = Visitor.new(params[:visitor])
    if @visitor.save
      flash[:notice] = "New visitor successfully created"
      redirect_to visitors_path
    else
      render new_visitor_path
    end
    
  end

  def list
    @visitors = Visitor.find(:all)

  end
end

app/controllers/visitors_controller.rb
require 'mime/types'
require 'spreadsheet'
require 'action_mailer'

class VisitorsController < ApplicationController
  before_filter :login_required

  Mime::Type.register "application/vnd.ms-excel", :xls


  autocomplete :visitor, :name, :extra_data => [:mobile_no, :age, :address, :gender, :visitor_type, :id]
  autocomplete :visitor, :mobile_no, :extra_data => [:name, :age, :address, :gender, :visitor_type, :id]

  def get_autocomplete_items(parameters)
    items = super(parameters)
    items = items.where(:is_delete => false)
  end

  def index
    @search_value  = params[:search_value]
    if @search_value
      @visitors = Visitor.search @search_value, :conditions => { :is_delete => false }
    else 
      @visitors = Visitor.where(:is_delete => false).order(:name,:address).paginate(:page => params[:page], :per_page => 15)
    end
  end

  def show
    @visitor = Visitor.find(params[:id], :conditions => ["is_delete = ?", false])
    @registrations = @visitor.registrations.where(:is_delete => false)
    respond_to do |format|
      format.xls { create_excel_and_send( @visitor, @registrations ) }
      format.html { render :show }
      format.js { render :json => @visitor }
    end
  end

  def new
    @visitor = Visitor.new
    @visitor[:gender] = "male"
    @visitor[:is_physically_challenged] = 'false'
    @visitor[:is_guide] = 'false'
    @visitor[:is_driver_along] = 'false'
    @visitor[:is_driver_accom_req] = 'false'
    @visitor[:is_driver_in_gyan] = 'false'
    @visitor[:is_special_care_req] = 'false'
#    @accompany_visitors = AccompanyVisitor.new
    @registration = Registration.new
    @registration.visitor = @visitor
    @event_list = Event.where(:is_delete => false, :is_active => true)
  end

  def edit
    @visitor = Visitor.find(params[:id], :conditions => ["is_delete = ?", false])
    @visitor.dob = @visitor.dob.strftime("%d %B %Y")
  end

=begin
  def checkinfacebox
    @visitor = Visitor.find(params[:visitor_id], :conditions => ["is_delete = ?", 0])
    @checkin = Checkin.new
    @checkin.visitor = @visitor
    @building = Building.new
    @room = Room.new
    ## @event_list = Event.find(:all, :conditions => ["is_delete = ?", 0])
    @checkin.event = @visitor.event
    @building_list = Building.find(:all, :conditions => ["is_delete = ? and no_of_rooms > 0", 0])
    @room_list = [""]
    @floor_list = [""]
    @coll = ["BK" ,"Non BK" ,"Teacher" ,"Service" ] 
    render :layout => "aboutblank"
  end
=end

  def create
    if params[:new_vis_reg_save] or params[:new_vis_reg_cont]
      @visitor = Visitor.new(params[:visitor])
      @event_list = Event.where(:is_delete => false, :is_active => true)
      
      if @visitor.dob == nil
        @visitor.dob = get_dob_from_age(@visitor.age)
      else
        @visitor.age = Time.now.strftime("%Y").to_i - (@visitor.dob.nil? ? Time.now.strftime("%Y").to_i : @visitor.dob.strftime("%Y").to_i)
      end

      if @visitor.save
        flash[:notice] = "Visitor #{@visitor.name.capitalize} successfully created"
      else
        flash[:notice] = nil
        render new_visitor_path
      end
    else
      visitor_id = (params[:registration][:visitor_id])
      @visitor = Visitor.where(:id => visitor_id, :is_delete => false).first
      event_id = (params[:registration][:event_id])
      @existing_registration = Registration.where(:visitor_id => visitor_id, :event_id =>event_id , :is_delete => false).first
      if @existing_registration.nil? == false
        flash[:notice] = "#ERROR# Visitor is already registered "
        redirect_to new_visitor_path
        return
      end
    end

    if @visitor.nil? == false
      @registration = Registration.new(params[:registration])
      @registration.visitor = @visitor
      if @registration.save
        unless params[:accompany_visitors].blank?
          params[:accompany_visitors].each do |accompany_visitor|
            acc_visitor = AccompanyVisitor.new(accompany_visitor)
            acc_visitor.registration_id = @registration.id
            acc_visitor.event_id = @registration.event_id
            acc_visitor.save
          end
        end
        if params[:new_vis_reg_save] or params[:reg_save]
          redirect_to registrations_path
        else
          redirect_to new_visitor_path
        end
      else
        render new_visitor_path
      end
    else
      render new_visitor_path
    end
  end

  def update
    @visitor = Visitor.find(params[:id])
    temp_visitor = Visitor.new(params[:visitor])

    puts ' temp ' + temp_visitor.dob.strftime("%D")
    puts ' old ' + @visitor.dob.strftime("%D")

    if temp_visitor.dob.strftime("%D") != @visitor.dob.strftime("%D")
      params[:visitor][:age] = Time.now.strftime("%Y").to_i - (temp_visitor.dob.nil? ? Time.now.strftime("%Y").to_i : temp_visitor.dob.strftime("%Y").to_i)
    else
      if temp_visitor.age != @visitor.age
        params[:visitor][:dob] = get_dob_from_age(temp_visitor.age)
      end
    end

    if @visitor.update_attributes(params[:visitor])
      flash[:notice] = "Visitor successfully updated"
      redirect_to visitors_path
    else
      render 'edit'
    end
  end

  def destroy
    @visitor = Visitor.find(params[:id])
    @visitor.is_delete = true
    if @visitor.save 
      temp_registration = @visitor.registrations.where(:is_delete => false)
      temp_checkin = Checkin.find(:all,:conditions => ["visitor_id = ?", @visitor.id])
      for t_r in temp_registration
        t_r.update_attribute(:is_delete,true)
      end
      for t_c in temp_checkin
        t_c.update_attribute(:is_delete,true)
      end
      flash[:notice] = "Visitor #{@visitor.name} has been deleted" 
      redirect_to visitors_path
    else
      flash[:notice] = "#ERROR#Can not delete Visitor #{@visitor.name} " 
      redirect_to visitors_path
    end
  end

  def get_dob_from_age age
    dob_year = Time.now.strftime("%Y").to_i - age
    dob_mon = Time.now.strftime("%b")
    dob_time = dob_mon + " " + dob_year.to_s
    dob = Time.parse(dob_time)
    #return dob.strftime("%d%m%y")
    return dob.strftime("%Y-%m-%d")
  end

  # Adding form fields
  def add_fields_1
    render :partial => "add_fields"
  end

  # Adding form fields
  def add_fields_2
    render :partial => "add_fields2"
  end

  # Adding additional form fields
  def additional_info
    render :partial => "additional_info"
  end
  
  # Adding accompany form fields
  def add_accompany_info
    render :partial => "accompany_info"
  end

  def create_excel_and_send (visitor, registrations)
    file_name = "#{visitor.name}.xls"
    file_book = Spreadsheet::Workbook.new
    file_sheet = file_book.create_worksheet(:name => "#{visitor.name}")
    
    write_excel(file_sheet, visitor, registrations) 

    file_book.write "#{RAILS_ROOT}/public/downloads/#{file_name}"
    file_path = "#{RAILS_ROOT}/public/downloads/#{file_name}"
    send_file file_path, :type => 'application/vnd.ms-excel'
  end

  def write_excel(sheet, visitor, registrations)
     row_counter = 0
     sheet.row(row_counter).default_format = Spreadsheet::Format.new(:weight=>"bold",:color=>"red",:pattern  => 1,:pattern_fg_color => "yellow")

     row_counter += 1
     sheet.row(row_counter).insert 0, "Name"
     sheet.row(row_counter).insert 1, visitor.name
     sheet.row(row_counter).insert 3, "DOB"
     sheet.row(row_counter).insert 4, visitor.dob.strftime("%d-%b-%Y")

     row_counter += 1
     sheet.row(row_counter).insert 0, "Address"
     sheet.row(row_counter).insert 1, visitor.address
     sheet.row(row_counter).insert 3, "Age"
     sheet.row(row_counter).insert 4, visitor.age

     row_counter += 1
     sheet.row(row_counter).insert 0, "Gender"
     sheet.row(row_counter).insert 1, visitor.gender.downcase == "female" ? "Female" : "Male"
     sheet.row(row_counter).insert 3, "Contact No."
     sheet.row(row_counter).insert 4, visitor.mobile_no


     row_counter += 1
     sheet.row(row_counter).insert 0, "Type"
     sheet.row(row_counter).insert 1, visitor.visitor_type.upcase
     sheet.row(row_counter).insert 3, "Email"
     sheet.row(row_counter).insert 4, (visitor.email.nil? || @visitor.email=='') ? "N/A": @visitor.email
#     sheet.row(row_counter).insert 3, event_name
#     sheet.row(row_counter).insert 3, event_name

     row_counter += 2
     sheet.row(row_counter).default_format = Spreadsheet::Format.new(:weight=>"bold")
     sheet.row(row_counter).insert 0, "S.No."
     sheet.row(row_counter).insert 1, "Event"
     sheet.row(row_counter).insert 2, "Registration Date"
     sheet.row(row_counter).insert 3, "Accompanying Male"
     sheet.row(row_counter).insert 4, "Accompanying Female"
#     sheet.row(row_counter).insert 5, ")"
#     sheet.row(row_counter).insert 6, "CENTER ADDRESS"
#     sheet.row(row_counter).insert 7, "CENTER NAME"
#     sheet.row(row_counter).insert 8, "ZONE"

     registrations.length.times do |serial_no|
       registration = registrations[serial_no]
       row_counter += 1 
       sheet.row(row_counter).insert 0, (serial_no+1)
       sheet.row(row_counter).insert 1, registration.event.name
       sheet.row(row_counter).insert 2, registration.created_at.strftime("%d-%b-%Y")
       sheet.row(row_counter).insert 3, registration.accompanying_males.nil? ? '0' : registration.accompanying_males
       sheet.row(row_counter).insert 4, registration.accompanying_females.nil? ? '0' : registration.accompanying_females
#       sheet.row(row_counter).insert 5, participants[serial_no].in_gyan
#       sheet.row(row_counter).insert 6, addresses[serial_no].addr1
#       sheet.row(row_counter).insert 7, Centre.find_by_id(centres[serial_no].id).name
#       sheet.row(row_counter).insert 8, zones[serial_no].name
     end
  end

end

app/helpers/visitor_helper.rb
module VisitorHelper
  def gender val
    val.capitalize
  end
end

app/views/visitors/_accompany_info.haml
%tr
  %td
    = label_tag :name, 'Accompanied Visitor*'
  %td
    = text_field_tag 'accompany_visitors[][name]', "", :class => 'text_feld_area'
  %td
    = label_tag :gender, 'Gender*'
    = select_tag 'accompany_visitors[][gender]', options_for_select(['Male', 'Female'], ""), :include_blank => "Select"
  %td
    = label_tag :visitor_type, 'Visitor Type*'
    = select_tag 'accompany_visitors[][visitor_type]', options_for_select(VISITOR_TYPE, ""), :include_blank => "Select"
  %td
    %span.delete_accompany_info= image_tag('Minus.png')

:javascript
  $('.delete_accompany_info').live('click', function() {
    $(this).parent().parent().remove();
  });

app/views/visitors/_add_fields.html.haml
%td
  = label_tag :in_gyan_years, 'In Gyan years*'
%td
  = number_field_tag "visitor[in_gyan_years]", "#{!params["visitor"].blank? ? params["visitor"]["in_gyan_years"] : !@visitor.blank? ? @visitor.in_gyan_years : nil}" , :class => 'text_feld_area'
%td
  = label_tag :centre_addr, 'Centre Address*'
%td
  = text_area_tag "visitor[centre_addr]", "#{!params["visitor"].blank? ? params["visitor"]["centre_addr"] : !@visitor.blank? ? @visitor.centre_addr : nil}", :size=> "20x1"

app/views/visitors/edit.html.haml
%div{:class=>"mid_bg_add text_add_6 padd25bt padd20tp-1", :cellspacing=>"2", :cellpadding=>"2", :border=>"0"}
  = render :partial => 'form'

app/views/visitors/index.html.haml
= javascript_include_tag 'visitor', 'jquery.min.js', 'jquery-ui.min.js', 'jquery_ujs.js', 'autocomplete-rails.js'
= stylesheet_link_tag 'jquery-ui-1.8.2.custom'
%div{:class=>"mid_bg_add_visitors text_add_6 padd25bt padd20tp-1", :cellspacing=>"2", :cellpadding=>"2"}
  .div_link{ :align => "right" }
    - form_tag ('/search/visitors') do
      = search_field_tag('search_value', @search_value)
      = submit_tag ('Search Visitors')
    - form_tag ('/search/visitors') do
      = autocomplete_field_tag 'name', '', visitors_autocomplete_visitor_name_path 
    = render "shared/flash_messages"
  .div_link
    = link_to image_tag('newvisitor.png',:title=>'Click to add new visitor',:mouseover => 'newvisitorover.png', :height=>40), new_visitor_path
  .paginate_ss
    = will_paginate
  .wrapper_vistors
    .row_hover
      %table{:width=>"980px",:style => "margin-left:15px",:cellpadding=>"0", :cellspacing=>"0"}
        %tbody
          %tr{:style => "background-color: #3A82F1"}
            %td
              &nbsp;
              %b Name
            %td
              %b Age
            %td
              %b Gender
            %td
              %b Address
            %td
              %b Mobile
            %td
              %b Visitor Type
            %td{:colspan => 5}
          - @visitors.each do |visitor|
            %tr.datarow
              %td
                &nbsp;
                = visitor.name
              %td
                = visitor.age
              %td
                = gender(visitor.gender)
              %td
                = visitor.address
              %td
                = visitor.mobile_no
              %td
                = visitor.visitor_type
              %td{:align => "center"}
                = link_to image_tag('view.png',:title => "View Record"), visitor_path(visitor.id)
              %td{:align => "center"}
                = link_to image_tag('edit.png', :title => "Edit '#{visitor.name}'"), edit_visitor_path(visitor.id)
              %td{:align => "center"}
                - if can? :update, @user
                  = link_to image_tag('delete.png', :title => "Delete '#{visitor.name}'"), visitor_path(visitor.id), :confirm=>"Are you sure to delete #{visitor.name}?", :method => :delete
    .paginate_ss
      = will_paginate

app/views/visitors/list.html.haml
= debug @visitors

app/views/visitors/new.html.haml
%div{:class=>"mid_bg_add text_add_6 padd25bt padd20tp-1", :cellspacing=>"2", :cellpadding=>"2", :border=>"0"}
  = render :partial => "regform"

app/views/visitors/show.html.haml
%div{:class=>"show_page text_add_6 padd25bt padd20tp-1", :cellspacing=>"2", :cellpadding=>"2"}
  %table{:class => "table-structure_show_page", :cellpadding=>"10", :cellspacing=>"10", :border=>0}
    %tbody
      %tr
        %td{:colspan => 3,:height => "40px"}
          .header_font
            = @visitor.name.capitalize
        %td{:align => "right"}
          = link_to button_to(" Go Back "),visitors_path, :method => "get", :title => "Go back to list"
      %tr
        %td{:colspan => 4}
          %hr
      %tr
        %td
          %b= label :name, 'Name'
        %td
          = text_field_tag 'name', @visitor.name.upcase, :disabled => true, :class => 'text_feld_area_show_page'
        %td
          %b= label :dob, 'Date of Birth'
        %td
          = text_field_tag 'dob', @visitor.dob.strftime("%d-%b-%Y"), :disabled => true, :class => 'text_feld_area_show_page'
      %tr
        %td
          %b= label :address, 'Address'
        %td
          = text_area_tag 'address', @visitor.address, :size=> "30x2", :disabled => true, :style => "font-size:12px;"
        %td
          %b= label :age, 'Age (Yrs)'
        %td
          = text_field_tag 'age', @visitor.age, :disabled => true, :class => 'text_feld_area_smaller'
      %tr
        %td
          %b= label :gender, 'Gender'
        %td
          = text_field_tag 'dob', @visitor.gender.downcase == "female" ? "Female" : "Male", :disabled => true, :class => 'text_feld_area_small'
        %td
          %b= label :mobile_no, 'Contact No'
        %td
          = text_field_tag 'mobile_no', @visitor.mobile_no, :class => 'text_feld_area_show_page', :disabled => true
      %tr 
        -#
          %td
            %b= label :phyc_chal, 'Physically challenged'
          %td
            = text_field_tag 'phyc_chal', (@visitor.is_physically_challenged.to_s=="true") ? "YES" : "NO", :class => 'text_feld_area_smaller', :disabled => true
        %td
          %b= label :visitor_type, 'Visitor Type'
        %td
          = text_field_tag 'visitor', @visitor.visitor_type.upcase, :class => 'text_feld_area_small', :disabled => true
      - if @visitor.visitor_type.upcase == "BK"
        %tr
          %td
            %b= label :in_gyan, 'In Gyan'
          %td
            = text_field_tag 'in_gyan', "#{@visitor.in_gyan_years} Years", :class => 'text_feld_area_small', :disabled => true
          %td
            %b= label :center_addr, 'Center Address'
          %td
            = text_area_tag 'center_addr', @visitor.centre_addr, :size=> "30x2", :disabled => true, :style => "font-size:12px;"
      %tr
        %td
          %b= label :designation, 'Designation'
        %td
          = text_field_tag 'designation', (@visitor.designation.nil? || @visitor.designation=='')? "N/A" : @visitor.designation.upcase, :class => 'text_feld_area_show_page', :disabled => true
        %td
          %b= label :organisation, 'Organisation'
        %td
          = text_field_tag 'organisation', (@visitor.organisation.nil? || @visitor.organisation=='') ? "N/A" : @visitor.organisation.upcase, :class => 'text_feld_area_show_page', :disabled => true
      %tr
        %td
          %b= label :email, 'E-mail'
        %td
          = text_field_tag 'email', (@visitor.email.nil? || @visitor.email=='') ? "N/A" : @visitor.email.downcase, :class => 'text_feld_area_show_page', :disabled => true
        %td
          %b= label :qualification, 'Qualification'
        %td
          = text_field_tag 'qualification', (@visitor.qualification.nil? || @visitor.qualification=='') ? "N/A" : @visitor.qualification.upcase, :class => 'text_feld_area_show_page', :disabled => true
      -#
        %tr
          %td
            %b= label :transport_mode, 'Mode of Transport'
          %td
            = text_field_tag 'transport_mode', (@visitor.transport_mode.nil? || @visitor.transport_mode=='') ? "N/A" : @visitor.transport_mode.upcase, :class => 'text_feld_area_show_page', :disabled => true
          %td
            %b= label :isguide, 'Is-Guide'
          %td
            = text_field_tag 'isguide', (@visitor.is_guide.to_s=="true") ? "YES" : "NO", :class => 'text_feld_area_smaller', :disabled => true
        %tr
          %td
            %b= label :isdriveralong, 'Is driver along'
          %td
            = text_field_tag 'isdriveralong', (@visitor.is_driver_along.to_s=="true") ? "YES" : "NO", :class => 'text_feld_area_smaller', :disabled => true
        - if @visitor.is_driver_along.to_s=="true"
          %tr
            %td
              %b= label :driver_name, 'Driver name'
            %td
              = text_field_tag 'driver_name', (@visitor.driver_name.nil? || @visitor.driver_name=='')? "N/A" : @visitor.driver_name.upcase, :class => 'text_feld_area_show_page', :disabled => true
            %td
              %b= label :driver_contact_no, 'Driver contact'
            %td
              = text_field_tag 'driver_contact_no', @visitor.driver_contact_no.nil? ? "N/A" : @visitor.driver_contact_no, :class => 'text_feld_area_show_page', :disabled => true
          %tr
            %td
              %b= label :driver_accom, 'Need driver accom'
            %td
              = text_field_tag 'driver_accom', (@visitor.is_driver_accom_req.to_s=="true") ? "YES" : "NO", :class => 'text_feld_area_smaller', :disabled => true
            %td
              %b= label :driver_ingyan, 'Driver in gyan'
            %td
              = text_field_tag 'driver_ingyan', (@visitor.is_driver_in_gyan.to_s=="true") ? "YES" : "NO", :class => 'text_feld_area_smaller', :disabled => true
        %tr
          %td
            %b= label :special_care, 'Need special care'
          %td
            = text_field_tag 'special_care', (@visitor.is_special_care_req.to_s=="true") ? "YES" : "NO", :class => 'text_feld_area_smaller', :disabled => true
        %tr
          %td
            %b= label :medicine, 'Medicine req'
          %td
            = text_field_tag 'medicine', (@visitor.medicine_requirement.nil? || @visitor.medicine_requirement=='') ? "N/A" : @visitor.medicine_requirement.upcase, :class => 'text_feld_area_show_page', :disabled => true
          %td
            %b= label :remarks, 'Remarks'
          %td
            = text_field_tag 'remarks', (@visitor.remarks.nil? || @visitor.remarks=='') ? "N/A" : @visitor.remarks.upcase, :class => 'text_feld_area_show_page', :disabled => true 
      %tr
        %td{:colspan => 4}
          %hr
          %hr
      - if @visitor.id != 0
        %tr 
          %td{:align => "center",:colspan => 5}
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            %b Registration Details
            %hr
            %hr
        %tr          
          %td
            &nbsp;
            %b Accompanying persons(Male)
          %td
            %b Accompanying persons (Female)
          %td
            %b Event
          %td
            %b Registration Date
          %td{:colspan => 5}
        - @registrations.each do |registration|
          - visitor = registration.visitor
          - event = registration.event
          %tr.datarow        
          %td
            &nbsp;
            = registration.accompanying_males.nil? ? '0' : registration.accompanying_males
          %td
            = registration.accompanying_females.nil? ? '0' : registration.accompanying_females
          %td
            = link_to registration.event.name, event_path(event.id)
          %td
            = registration.created_at.strftime("%d-%b-%Y")
          %td{:align => "right"}
            = link_to image_tag('view.png',:title => "View Record"), registration_path(registration.id)
          %td{:align => "right"}
            = link_to image_tag('edit.png', :title => "Edit '#{visitor.name}'"), edit_registration_path(registration.id)
          %td{:align => "right"}
            - if can? :update, @user
              = link_to image_tag('delete.png', :title => "Delete '#{visitor.name}'"), registration_path(registration.id), :confirm=>"Are you sure to delete #{visitor.name}?", :method => :delete
          
         