config/routes.rb
Orc::Application.routes.draw do

  match "search/visitors" => 'visitors#index'
  get 'visitors/autocomplete_visitor_name'
  get 'visitors/autocomplete_visitor_mobile_no'

  resources :users
  resources :user_sessions
  match 'users/new' => 'users#new', :as => :signup
  match 'user_sessions/logout/:id' => 'user_sessions#logout', :as => :logout
  match 'user_sessions/new' => 'user_sessions#new', :as => :login
  
  get "user_sessions/new"
  get "users/new"
  get "users/edit"
  get "events/create"
  match 'visitors/checkinfacebox/:registration_id' => 'visitors#checkinfacebox', :as => :checkinfacebox_visitor
  match 'visitors/save_and_continue' => 'visitors#save_and_continue', :as => :save_and_continue
  match 'utilities/uploadexcel' => 'utilities#uploadexcel', :as => :uploadexcel
  match 'utilities/user_list' => 'utilities#user_list', :as => :user_list
  match 'utilities/building_list' => 'utilities#building_list', :as => :building_list
  match 'utilities/event_list' => 'utilities#event_list', :as => :event_list
  match 'utilities/usr_load' => 'utilities#usr_load', :as => :usr_load
  match 'utilities/visitor_load' => 'utilities#visitor_load', :as => :visitor_load
  match 'utilities/cancel_user' => 'utilities#cancel_user', :as => :cancel_user
  match 'utilities/building_load' => 'utilities#building_load', :as => :building_load
  match 'utilities/cancel_building' => 'utilities#cancel_building', :as => :cancel_building
  match 'utilities/event_load' => 'utilities#event_load', :as => :event_load
  match 'utilities/cancel_event' => 'utilities#cancel_event', :as => :cancel_event
  match 'utilities/download_user_list' => 'utilities#download_user_list', :as => :download_user_list
  match 'utilities/download_visitor_list' => 'utilities#download_visitor_list', :as => :download_visitor_list
  match 'utilities/download_building_list' => 'utilities#download_building_list', :as => :download_building_list
  match 'utilities/download_event_list' => 'utilities#download_event_list', :as => :download_event_list
  match 'buildings/add_rooms_to_building/:building_id' => 'buildings#add_rooms_to_building', :as => :add_rooms_to_building
  match 'buildings/add_rooms_to_building_view/:building_id' => 'buildings#add_rooms_to_building_view', :as => :add_rooms_to_building_view
  resources :utilities

  match 'events/:id/participants' => 'events#participants' , :as => :event_participants

     match 'home/index_list' => 'home#index_list', :as => :index_list

  resources :visitors do
    collection do
      post :add_fields_1
      post :add_fields_2
      post :additional_info
      post :add_accompany_info
    end
  end
  
  resources :checkins
  post 'checkins/inactivate/:id' => "checkins#inactivate", :as => :inactivate_checkin
  get 'checkins/print/:id' => "checkins#print", :as => :print_checkin
  
  resources :events 
  post 'events/inactivate/:id' => "events#inactivate", :as => :inactivate_event
  post 'events/activate/:id' => "events#activate", :as => :activate_event

  resources :accompany_visitors
  resources :registrations
  resources :buildings
  resources :rooms
  resources :checkins do
    collection do
      post :roomsearch
    end
  end
 

  get 'javascripts/checkin' => 'javascripts#checkin'
  get 'javascripts/visitor' => 'javascripts#visitor'
  get 'javascripts/event' => 'javascripts#event'
  get 'javascripts/regform' => 'javascripts#regform'

  

  root :to => "user_sessions#new"

end

app/models/event.rb
class Event < ActiveRecord::Base
  #has_many :registrations
  has_many :visitors, :through => :registrations
  has_many :registrations
#  has_many :checkins
  has_many :accompany_visitors
  before_create :set_default_values
  
  def set_default_values
    self.is_delete = false
    self.is_active = true
  end

  validates :name, :presence => true
  validates :start_date_time, :presence => true
  validates :end_date_time, :presence => true
  validates :location, :presence => true
end

app/controllers/events_controller.rb
require 'mime/types'
require 'spreadsheet'

class EventsController < ApplicationController

  before_filter :login_required

  load_and_authorize_resource

  Mime::Type.register "application/vnd.ms-excel", :xls
  
  def new
    @event = Event.new
  end
  
  def create
    @event = Event.new(params[:event])
    if !@event.start_date_time.nil? && !@event.end_date_time.nil? && @event.start_date_time > @event.end_date_time
      flash[:notice] = '#ERROR#Start date can\'t be more than end date'  
      render 'new'
    else
      if @event.save
         flash[:notice] = 'Done '
         redirect_to events_path
      else
         flash[:notice] = nil
         render 'new'
      end
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      redirect_to events_path
    else
      render 'edit'
    end
  end

  def edit
    @event = Event.find(params[:id])
    @event.start_date_time=@event.start_date_time.strftime("%d %B %Y")
    @event.end_date_time=@event.end_date_time.strftime("%d %B %Y")
  end

  def show
    @event = Event.find(params[:id])
    @registrations = Registration.where(:event_id => params[:id], :is_delete => false)
    participants_list = []
    @registrations.each do |registration|
	participants_list += registration.participants
    end
    @participants = participants_list.paginate(:page => params[:page], :per_page => 15)
    #@participants = Registration.where(:event_id => params[:id], :is_delete => false).paginate(:page => params[:page], :per_page => 15)
    respond_to do |format|
      format.xls { create_excel_and_send( @event, participants_list) }
      format.html { render :show }
    end
  end

  def destroy 
    @event = Event.find(params[:id])
    ## @event.destroy
    @event.is_delete = true
    if @event.save 
      temp_registration = Registration.find(:all,:conditions => ["event_id = ?", @event.id])
      temp_checkin = Checkin.find(:all,:conditions => ["event_id = ?", @event.id])
      for t_r in temp_registration
        t_r.update_attribute(:is_delete,true)
      end
      for t_c in temp_checkin
        t_c.update_attribute(:is_delete,true)
      end
      flash[:notice] = "Event #{@event.name} has been deleted" 
    else
      flash[:notice] = "#ERROR#Error in deleting event #{@event.name} " 
    end
    redirect_to events_path
  end    

  def index
    @events = Event.where(:is_delete => false).order("start_date_time DESC").paginate(:page => params[:page], :per_page => 15)
  end

  def participants
    #@registrations = Registration.where(:event_id => params[:id], :is_delete => false).paginate(:page => params[:page], :per_page => 15)
    #@participants += @registration.participants
#    @participants = [1,2]
  end

  def inactivate
    @event = Event.where(:id => params[:id], :is_delete => false).first
    if @event.nil? == false
      @event.update_attribute(:is_active, false)
    end
    redirect_to events_path
  end

  def activate
    @event = Event.where(:id => params[:id], :is_delete => false).first
    if @event.nil? == false
      @event.update_attribute(:is_active, true)
    end
    redirect_to events_path
  end

  
  def create_excel_and_send (event, participants)
    file_name = "#{event.name}.xls"
    file_book = Spreadsheet::Workbook.new
    file_sheet = file_book.create_worksheet(:name => "#{event.name}")
    
    write_excel(file_sheet, event, participants) 

    file_book.write "#{RAILS_ROOT}/public/downloads/#{file_name}"
    file_path = "#{RAILS_ROOT}/public/downloads/#{file_name}"
    send_file file_path, :type => 'application/vnd.ms-excel'
  end

  def write_excel(sheet, event, participants)
     row_counter = 0
     sheet.row(row_counter).default_format = Spreadsheet::Format.new(:weight=>"bold",:color=>"red",:pattern  => 1,:pattern_fg_color => "yellow")

     row_counter += 1
     sheet.row(row_counter).insert 0, "Name"
     sheet.row(row_counter).insert 1, event.name
#     sheet.row(row_counter).insert 3, "DOB"
#     sheet.row(row_counter).insert 4, visitor.dob.strftime("%d-%b-%Y")

     row_counter += 1
     sheet.row(row_counter).insert 0, "Start Date"
     sheet.row(row_counter).insert 1, event.start_date_time.strftime("%d-%b-%Y")
     sheet.row(row_counter).insert 3, "End Date"
     sheet.row(row_counter).insert 4, event.end_date_time.strftime("%d-%b-%Y")

     row_counter += 1
     sheet.row(row_counter).insert 0, "Capacity"
     sheet.row(row_counter).insert 1, event.capacity
     sheet.row(row_counter).insert 3, "Location"
     sheet.row(row_counter).insert 4, event.location


#     row_counter += 1
#     sheet.row(row_counter).insert 0, "Type"
#     sheet.row(row_counter).insert 1, visitor.visitor_type.upcase
#     sheet.row(row_counter).insert 3, "Email"
#     sheet.row(row_counter).insert 4, (visitor.email.nil? || @visitor.email=='') ? "N/A": @visitor.email
#     sheet.row(row_counter).insert 3, event_name
#     sheet.row(row_counter).insert 3, event_name

     row_counter += 2
     sheet.row(row_counter).default_format = Spreadsheet::Format.new(:weight=>"bold")
     sheet.row(row_counter).insert 0, "S.No."
     sheet.row(row_counter).insert 1, "Name"
     sheet.row(row_counter).insert 2, "Age"
     sheet.row(row_counter).insert 3, "Gender"
     sheet.row(row_counter).insert 4, "Mobile"
     sheet.row(row_counter).insert 5, "Visitor Type"
     sheet.row(row_counter).insert 6, "Address"
     sheet.row(row_counter).insert 7, "Email"
#     sheet.row(row_counter).insert 7, "CENTER NAME"
#     sheet.row(row_counter).insert 8, "ZONE"

     participants.length.times do |serial_no|
       participant = participants[serial_no]
       row_counter += 1 
       sheet.row(row_counter).insert 0, (serial_no+1)
       sheet.row(row_counter).insert 1, participant.name
       sheet.row(row_counter).insert 2, participant.age.nil? ? "NA" : participant.age
       sheet.row(row_counter).insert 3, participant.gender.capitalize
       sheet.row(row_counter).insert 4, participant.mobile_no
       sheet.row(row_counter).insert 5, participant.visitor_type
       sheet.row(row_counter).insert 6, participant.address
       sheet.row(row_counter).insert 7, participant.email
#       sheet.row(row_counter).insert 7, Centre.find_by_id(centres[serial_no].id).name
#       sheet.row(row_counter).insert 8, zones[serial_no].name
     end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= javascript_include_tag 'event'
%div{:class=>"mid_bg_add text_add_6 padd25bt padd20tp-1", :cellspacing=>"2", :cellpadding=>"2", :border=>"0"}
  = form_for @event do |f|
    = render "shared/flash_messages"
    = render "shared/error_messages", :target => @event
    %table{:class => "table-structure", :cellpadding=>"10", :cellspacing=>"20"}
      %tbody
        %tr
          %td{:colspan=>"4",:align=>"center"}
            .header_font
              = f.label :edit_event_info, ' Event Registration Form'
        %tr
          %td
            = f.label :name, 'Event Name*'
          %td
            = f.text_field :name, :class => 'text_feld_area'
        %tr
          %td
            = f.label :start_date_time, 'Start Date*'
          %td
            = f.text_field :start_date_time, :class => 'text_feld_area'
          %td
            = f.label :end_date_time, 'End Date*'
          %td
            = f.text_field :end_date_time, :class => 'text_feld_area'
        %tr
          %td 
            = f.label :capacity, 'Capacity'
          %td
            = f.number_field :capacity, :in => [1,100000], :step => 1, :class => 'text_feld_area'
          %td  
            = f.label :location, 'Location*'
          %td
            = f.text_field :location, :class => 'text_feld_area'
        %tr
          %td{:colspan => "2",:align=>"right"}
            - if @event.id.nil?
              = submit_tag 'Submit', :disable_with => 'Submit'
            - else
              = submit_tag 'Update', :disable_with => 'Update'
          %td{:colspan => "2",:align=>"left"}
            = link_to button_to("Cancel"),events_path, :method => "get"

app/views/events/edit.html.haml
= render :partial => 'form'

app/views/events/index.html.haml
%div{:class=>"mid_bg_add text_add_6 padd25bt padd20tp-1", :cellspacing=>"2", :cellpadding=>"2", :border=>"0"}
  .div_link
    = link_to image_tag('newevent.png',:title=>'Click to add new event',:mouseover => 'neweventover.png', :height=>40), new_event_path
  .paginate_ss
    = will_paginate
  .wrapper_event
    .row_hover
      %table{:width=>"920px",:style => "margin-left:15px",:cellpadding=>"0", :cellspacing=>"0"}
        %tbody
          %tr{:style => "background-color: #3A82F1"}
            %td
              &nbsp;
              %b Event Name
            %td
              %b Start Date
            %td
              %b End Date
            %td
              %b Capacity
            %td
              %b Location
            %td
              %b Is Active
            %td{:colspan => 4}
          - @events.each do |event|
            %tr.datarow
              %td
                &nbsp;
                = link_to event.name, event_path(event.id)
              %td
                = event.start_date_time.strftime("%d-%b-%Y")
              %td
                = event.end_date_time.strftime("%d-%b-%Y")
              %td
                = event.capacity
              %td
                = event.location
              %td
                = event.is_active ? "Yes" : "No"
              %td
                -if event.is_active
                  = link_to "Inactivate", inactivate_event_path(event.id), :method => :post
                - else
                  = link_to "Activate", activate_event_path(event.id), :method => :post
              %td{:align => "center"}
                = link_to image_tag('view.png',:title => "View Record"), event_path(event.id)
              %td{:align => "center"}
                = link_to image_tag('edit.png',:title => "Edit '#{event.name}'"), edit_event_path(event.id)
              %td{:align => "center"}
                - if can? :update, @user
                  = link_to image_tag('delete.png',:title => "Delete '#{event.name}'"), event_path(event.id), :method => :delete, :confirm=>"Are you sure to delete event #{event.name} ?"
  .paginate_ss
    = will_paginate

app/views/events/new.html.haml
= render :partial => 'form'

app/views/events/participants.html.haml
%div
  .paginate_ss
    = will_paginate @participants
  .wrapper_vistors
    .row_hover
      %table{:width=>"980px",:style => "margin-left:15px",:cellpadding=>"0", :cellspacing=>"0"}
        %tbody
          %tr{:style => "background-color: #3A82F1"}
            %td
              &nbsp;
              %b Name
            %td
              %b Age
            %td
              %b Gender
            %td
              %b Address
            %td
              %b Mobile
            %td
              %b Visitor Type
            %td{:colspan => 5}
          - @participants.each do |registration|
            - visitor = registration.visitor
            %tr.datarow
              %td
                &nbsp;
                = link_to visitor.name, visitor_path(visitor.id)
              %td
                = visitor.age
              %td
                = gender(visitor.gender)
              %td
                = visitor.address
              %td
                = visitor.mobile_no
              %td
                = visitor.visitor_type
    .paginate_ss
    = will_paginate @participants

app/views/events/show.html.haml
%div{:class=>"show_page text_add_6 padd25bt padd20tp-1", :cellspacing=>"2", :cellpadding=>"2"}
  %table{:class => "table-structure_show_page", :cellpadding=>"10", :cellspacing=>"10", :border=>0}
    %tbody
      %tr
        %td{:colspan => 3,:height => "40px"}
          .header_font
            = "Event Name. :- #{@event.name}"
        %td{:align => "center"}
          = link_to " Download Excel ", event_path(@event, :format => :xls), :title => "Download Excel File for the Event"
        %td{:align => "right"}
          = link_to button_to(" Go Back "),events_path, :method => "get", :title => "Go back to list"
      %tr
        %td{:colspan => 4}
          %hr
      %tr
        %td
          %b= label :name, 'Event Name'
        %td
          = text_field_tag 'name', @event.name, :disabled => true, :class => 'text_feld_area_show_page'
        %td
          %b= label :start_date_time, 'Start Date'
        %td
          = text_field_tag 'start_date_time', @event.start_date_time, :disabled => true, :class => 'text_feld_area_show_page'
      %tr
        %td
          %b= label :end_date_time, 'End Date'
        %td
          = text_area_tag 'end_date_time',@event.end_date_time, :disabled => true, :class => 'text_feld_area_show_page'
        %td
          %b= label :capacity, 'Capacity'
        %td
          = text_field_tag 'capacity', @event.capacity, :disabled => true, :class => 'text_feld_area_show_page'
      %tr
        %td
          %b= label :location, 'Location'
        %td
          = text_field_tag 'location', @event.location, :disabled => true, :class => 'text_feld_area_show_page'
%div
  .paginate_ss
    = will_paginate @participants
  .wrapper_vistors
    .row_hover
      %table{:width=>"980px", :cellpadding=>"0", :cellspacing=>"0"}
        %tbody
          %tr{:style => "background-color: #3A82F1"}
            %td
              &nbsp;
              %b Name
            %td
              %b Gender
            %td
              %b Visitor Type
            %td{:colspan => 5}
          =# debug @participants
          -# @participants.each do |registration|
            - visitor = registration.visitor
          - @participants.each do |participant|
            %tr.datarow
              %td
                &nbsp;
                = link_to participant.name, registration_path(participant.registration_id)
              %td
                = gender(participant.gender)
              %td
                = participant.visitor_type
    .paginate_ss
    = will_paginate @participants