config/routes.rb
Orc::Application.routes.draw do

  match "search/visitors" => 'visitors#index'
  get 'visitors/autocomplete_visitor_name'
  get 'visitors/autocomplete_visitor_mobile_no'

  resources :users
  resources :user_sessions
  match 'users/new' => 'users#new', :as => :signup
  match 'user_sessions/logout/:id' => 'user_sessions#logout', :as => :logout
  match 'user_sessions/new' => 'user_sessions#new', :as => :login
  
  get "user_sessions/new"
  get "users/new"
  get "users/edit"
  get "events/create"
  match 'visitors/checkinfacebox/:registration_id' => 'visitors#checkinfacebox', :as => :checkinfacebox_visitor
  match 'visitors/save_and_continue' => 'visitors#save_and_continue', :as => :save_and_continue
  match 'utilities/uploadexcel' => 'utilities#uploadexcel', :as => :uploadexcel
  match 'utilities/user_list' => 'utilities#user_list', :as => :user_list
  match 'utilities/building_list' => 'utilities#building_list', :as => :building_list
  match 'utilities/event_list' => 'utilities#event_list', :as => :event_list
  match 'utilities/usr_load' => 'utilities#usr_load', :as => :usr_load
  match 'utilities/visitor_load' => 'utilities#visitor_load', :as => :visitor_load
  match 'utilities/cancel_user' => 'utilities#cancel_user', :as => :cancel_user
  match 'utilities/building_load' => 'utilities#building_load', :as => :building_load
  match 'utilities/cancel_building' => 'utilities#cancel_building', :as => :cancel_building
  match 'utilities/event_load' => 'utilities#event_load', :as => :event_load
  match 'utilities/cancel_event' => 'utilities#cancel_event', :as => :cancel_event
  match 'utilities/download_user_list' => 'utilities#download_user_list', :as => :download_user_list
  match 'utilities/download_visitor_list' => 'utilities#download_visitor_list', :as => :download_visitor_list
  match 'utilities/download_building_list' => 'utilities#download_building_list', :as => :download_building_list
  match 'utilities/download_event_list' => 'utilities#download_event_list', :as => :download_event_list
  match 'buildings/add_rooms_to_building/:building_id' => 'buildings#add_rooms_to_building', :as => :add_rooms_to_building
  match 'buildings/add_rooms_to_building_view/:building_id' => 'buildings#add_rooms_to_building_view', :as => :add_rooms_to_building_view
  resources :utilities

  match 'events/:id/participants' => 'events#participants' , :as => :event_participants

     match 'home/index_list' => 'home#index_list', :as => :index_list

  resources :visitors do
    collection do
      post :add_fields_1
      post :add_fields_2
      post :additional_info
      post :add_accompany_info
    end
  end
  
  resources :checkins
  post 'checkins/inactivate/:id' => "checkins#inactivate", :as => :inactivate_checkin
  get 'checkins/print/:id' => "checkins#print", :as => :print_checkin
  
  resources :events 
  post 'events/inactivate/:id' => "events#inactivate", :as => :inactivate_event
  post 'events/activate/:id' => "events#activate", :as => :activate_event

  resources :accompany_visitors
  resources :registrations
  resources :buildings
  resources :rooms
  resources :checkins do
    collection do
      post :roomsearch
    end
  end
 

  get 'javascripts/checkin' => 'javascripts#checkin'
  get 'javascripts/visitor' => 'javascripts#visitor'
  get 'javascripts/event' => 'javascripts#event'
  get 'javascripts/regform' => 'javascripts#regform'

  

  root :to => "user_sessions#new"

end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :building

  has_many :checkins
 
#  before_create :set_default_values
#
#  def set_default_values
#    self.is_delete = 0
#    self.is_ac = 0
#    self.is_extensible = 0
#    self.beds_extensible = 0
#    #self.empty_beds = 0
#    self.occupied_beds = 0
#  end
  validates :building_id, :presence => true
  validates :room_no, :presence => true
  validates :floor, :presence => true, :inclusion => (0..30), :numericality => true
  validates :total_beds, :presence => true, :inclusion => (0..200), :numericality => true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_filter :login_required
  def new
    @building = Building.find(params[:building_id])
    if @building
      @room = Room.new(:building => @building)
      @room_category = [1, 2]
    else
      redirect_to buildings_path
    end
  end

  def create
    #HACK- need to send building info from the form
    @building = Building.find(params[:room][:building])
    params[:room][:building] = @building
    @room = Room.new(params[:room])
    occupied_beds = @room.occupied_beds||0
    
    if @room.save
      @room.update_attribute(:empty_beds, @room.total_beds - @room.occupied_beds)
      @room.update_attribute(:occupied_beds, occupied_beds)
      redirect_to building_path(@building.id)
    else
      redirect_to new_room_path(@building.id)
    end
  end

  def index
    @rooms = Room.find(:all, :conditions => ["is_delete = ?", false])
  end

  def show 
    @room = Room.find(params[:id], :conditions => ["is_delete = ?", false])
    @checkins = @room.checkins.where(:is_delete => false)
  end

  def destroy 
    @room = Room.find(params[:id])
    ## @room.destroy
    @room.is_delete = true
    if @room.save 
      @building = Building.find(@room.building)
      #@building = @room.building
      @building.update_attribute(:no_of_rooms , @building.no_of_rooms - 1)

      temp_checkin = Checkin.find(:all,:conditions => ["room_id = ?", @room.id])
      for t_c in temp_checkin
        t_c.update_attribute(:is_delete,true)
      end
      flash[:notice] = "Room #{@room.room_no} has been deleted" 
    else
      flash[:notice] = "#ERROR#Error in deleting room #{@room.room_no} " 
    end
    redirect_to building_path(@room.building.id)
  end

  def edit 
    @room = Room.find(params[:id])
    @building = @room.building
    @room_category = [1, 2]
  end

  def update
    @room = Room.find(params[:id])
    @building = Building.find(params[:room][:building])
    params[:room][:building] = @building
    if @room.update_attributes(params[:room])
      redirect_to building_path(@building.id)
    else
      render 'edit'
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.haml
%div{:class=>"mid_bg_add_visitors text_add_6 padd25bt padd20tp-1", :cellspacing=>"2", :cellpadding=>"2", :border=>"0"}
  = form_for @room do |f|
    %table{:class => "table-structure", :cellpadding=>"10", :cellspacing=>"20"}
      %tbody
        %tr
          %td{:colspan=>"4"}
            .header_font
              = f.label :add_room, 'Add Rooms To "' + @building.name + '"'
        %tr
          %td
            = f.label :building, 'Building'
          %td{:colspan=>"3"}
            = f.text_field :building, :value => @building.id, :hidden => true
            = text_field_tag :building_name, @building.name, :readonly => true, :class => 'text_feld_area'
        %tr
          %td
            = f.label :room_no, 'Room No.*'
          %td
            = f.number_field :room_no, :step => 1, :class => 'text_feld_area'
          %td
            = f.label :floor, 'Floor*'
          %td
            = f.number_field :floor, :class => 'text_feld_area'
        %tr
          %td
            = f.label :total_beds, 'Total Beds*'
          %td
            = f.number_field :total_beds, :class => 'text_feld_area'
          %td
            = f.label :occupied_beds, 'Occupied Beds'
          %td
            = f.number_field :occupied_beds, :value => 0, :class => 'text_feld_area'
        %tr
          %td
            = f.label :category, 'Type/Category'
          %td
            = select :room, :category, @room_category
          %td
            = f.label :is_ac, 'Is AC?'
          %td
            = f.radio_button :is_ac , 0, :value=>"true" 
            No
            = f.radio_button :is_ac , 1
            Yes
        %tr
          %td{:colspan => "2",:align=>"right"}
            = submit_tag 'Submit', :disable_with => 'Submit'
          %td{:colspan => "2",:align=>"left"}
            = link_to button_to("Cancel"),buildings_path, :method => "get"

app/views/rooms/edit.html.haml
= render :partial => "form"

app/views/rooms/index.html.haml
%table
  %tr
    %th Room No.
    %th Empty Beds
    %th Total Beds
    %th Is AC
    %th Category
    %th Floor
  - @rooms.each do |room|
    %tr
      %td= room.room_no
      %td= room.empty_beds
      %td= room.occupied_beds
      %td= room.is_ac
      %td= room.category
      %td= room.floor
      %td= link_to "show", room_path(room.id)
      %td= link_to "edit", edit_room_path(room.id)
      %td= link_to "delete", room_path(room.id), :method => :delete

app/views/rooms/new.html.haml
= render :partial => "form"

app/views/rooms/show.html.haml
%div{:class=>"show_page text_add_6 padd25bt padd20tp-1", :cellspacing=>"2", :cellpadding=>"2"}
  %table{:class => "table-structure_show_page", :cellpadding=>"10", :cellspacing=>"10", :border=>0}
    %tbody
      %tr
        %td{:colspan => 3,:height => "40px"}
          .header_font
            = "Room No. :- #{@room.room_no}"
        %td{:align => "right"}
          = link_to button_to(" Go Back "),rooms_path, :method => "get", :title => "Go back to list"
      %tr
        %td{:colspan => 4}
          %hr
      %tr
        %td
          %b= label :room_no, 'Room No.'
        %td
          = text_field_tag 'room_no', @room.room_no, :disabled => true, :class => 'text_feld_area_show_page'
        %td
          %b= label :floor, 'Floor'
        %td
          = text_field_tag 'floor', @room.floor, :disabled => true, :class => 'text_feld_area_show_page'
      %tr
        %td
          %b= label :total_beds, 'Total Beds'
        %td
          = text_area_tag 'total_beds',@room.total_beds, :disabled => true, :class => 'text_feld_area_show_page'
        %td
          %b= label :occupied_beds, 'Occupied Beds'
        %td
          = text_field_tag 'occupied_beds', @room.occupied_beds, :disabled => true, :class => 'text_feld_area_show_page'
      %tr
        %td
          %b= label :category, 'Type/Category'
        %td
          = text_field_tag 'category', @room.category, :disabled => true, :class => 'text_feld_area_show_page'
        %td
          %b= label :is_ac, 'Is AC?'
        %td
          = text_field_tag 'is_ac', @room.is_ac, :class => 'text_feld_area_show_page', :disabled => true
      %tr
        %td{:colspan => 4}
          %hr
          %hr
      - if @room_no != 0
        %tr 
          %td{:align => "center",:colspan => 5}
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            %b Checkin Details
            %hr
            %hr
        %tr          
          %td
            &nbsp;
            %b Visitor Name
          %td
            %b Address
          %td
            %b Event
          %td
            %b Checkin Date
          %td
            %b Checkout Date
          %td{:colspan => 5}
        - @checkins.each do |checkin|
          -visitor = checkin.visitor
          -event = checkin.event
          %tr.datarow        
          %td
            &nbsp;
            - if checkin.visitor
              = link_to checkin.visitor.name, visitor_path(visitor.id)
          %td
            = checkin.visitor.address
          %td
            = link_to checkin.event.name, event_path(event.id)
          %td
            = checkin.checkin_date
          %td
            = checkin.checkout_date
          %td{:align => "center"}
            = link_to image_tag('view.png',:title => "View Record", :width => 15), checkin_path(checkin.id)
          %td{:align => "center"}
            = link_to image_tag('edit.png',:title => "Edit #{checkin.visitor.name}'s Checkin"), edit_checkin_path(checkin.id)
          %td{:align => "center"}
            - if can? :update, @user
              = link_to image_tag('delete.png',:title => "Delete #{checkin.visitor.name}'s Checkin", :width => 15), checkin_path(checkin.id), :method => :delete, :confirm=>"Are you sure to delete visitor #{checkin.visitor.name} checkin ?" 
          
         
     